project:
  type: default
  output-dir: _site
  render:
    - index.qmd

format:
  revealjs:
    output-file: index.html
    theme:
      - default
      - custom.scss
    slide-number: true
    code-line-numbers: true
    chalkboard: false
    preview-links: auto
    footer: "ASH 2025 | B-Cell Lymphoma Updates"
    width: 1600
    height: 900
    margin: 0.1
    center: false
    navigation-mode: linear
    controls-layout: edges
    controls-tutorial: false
    hash: true
    history: true
    transition: none
    background-transition: none
    simplemenu:
      barhtml:
        header: "<div class='menubar'><ul class='menu'></ul></div>"
      flat: false
      scale: 0.67
    filters:
      - reveal-auto-agenda
    revealjs-plugins:
      - simplemenu
    auto-agenda:
      bullets: numbered
      heading: Agenda
